version: '3.1'
services:
  app-lemon:
    container_name: app-lemon
    restart: always
    environment:
      - NODE_ENV=production
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    env_file:
      - .env
    volumes:
      - app-data:/src/app
  database:
    image: postgres
    container_name: lemondb
    environment:
      - POSTGRES_USER=lemon
      - POSTGRES_PASSWORD=123
    ports:
      - '5432:5432'
volumes:
  app-data:
