export enum CONSUMPTIONCLASSES {
  RESIDENCIAL = 'RESIDENCIAL',
  INDUSTRIAL = 'INDUSTRIAL',
  COMERCIAL = 'COMERCIAL',
  RURAL = 'RURAL',
  PODERPUBLICO = 'PODERPUBLICO',
}
export enum TARIFFMODALITY {
  BRANCA = 'BRANCA',
  AZUL = 'AZUL',
  VERDE = 'VERDE',
  CONVENCIONAL = 'CONVENCIONAL',
}
export enum CONNECTIONTYPES {
  MONOFASICO = 'MONOFASICO',
  BIFASICO = 'BIFASICO',
  TRIFASICO = 'TRIFASICO',
}
